HW#6 and HW#7
1dynamite/exadel-sandbox pull request #6
Opened 2022-04-03 18:32 UTC by 1dynamite

I have added login page, client-side validations, error-handling, interceptors, guards, etc

P.S. I still have 30 minutes before it hits Monday, the deadline. So, I have submitted the HWs in time.

2022-04-04 07:06 UTC, AudriusBaltusis requested changes
If this PR contains HW #7, you have to create components for header and footer

2022-04-04 07:06 UTC, AudriusBaltusis commented on client/src/app/dashboard/dashboard.component.ts
> +  user: any;
Please do not use `any`

2022-04-04 07:06 UTC, AudriusBaltusis commented on client/src/app/dashboard/dashboard.component.ts
> +  logout() {
Please add return type

2022-04-04 07:06 UTC, AudriusBaltusis commented on client/src/app/dashboard/dashboard.service.ts
> +  getUser() {
Please add return type everywhere

2022-04-04 07:06 UTC, AudriusBaltusis commented on client/src/app/login/login.service.ts
> +  login(loginData: LoginData): Observable<any> {
Please do no use `any`

2022-04-04 07:06 UTC, AudriusBaltusis commented on client/src/app/not-found/not-found.component.html
> +<p>Page not found(</p>
Typo `(`

2022-04-04 07:06 UTC, AudriusBaltusis commented on client/src/app/not-found/not-found.component.ts
> +  ngOnInit(): void {
Please remove empty `ngOnInit`

2022-04-04 10:33 UTC, 1dynamite commented
I am developing the UI based on the Figma design provided by Maxim (https://www.figma.com/file/EXv9NCHklgfbbhB4FfgaS0/Budgetify?node-id=0%3A1). This design does not have a footer and one big header. Instead, it is divided into three main columns. That's what I did with my dashboard component. But if you insist that I should have a footer and a header, then I will create them. What do you think?

2022-04-04 11:02 UTC, AudriusBaltusis commented
> I am developing the UI based on the Figma design provided by Maxim (https://www.figma.com/file/EXv9NCHklgfbbhB4FfgaS0/Budgetify?node-id=0%3A1). This design does not have a footer and one big header. Instead, it is divided into three main columns. That's what I did with my dashboard component. But if you insist that I should have a footer and a header, then I will create them. What do you think?

If there is no footer in design, then skip it. But header component is mandatory

2022-04-04 11:16 UTC, 1dynamite commented
I do have a header. 
![image](https://user-images.githubusercontent.com/43914259/161532683-85f6a60a-4614-40bb-ab44-5c5a7aaa4a4f.png)

2022-04-04 13:16 UTC, 1dynamite commented
Ok, I think I got you. I will extract those top-level bars (or headers) from the dashboard component and put them in separate files and import them.

2022-04-05 23:22 UTC, 1dynamite commented
![image](https://user-images.githubusercontent.com/43914259/161866732-36b2c5ae-0c41-4d9c-8850-363bc26b8a84.png)

2022-04-06 11:50 UTC, AudriusBaltusis approved these changes

2022-04-06 12:52 UTC, merged